./build/build_targets/gcc/release/test_01_math_tables.exe
./build/build_targets/gcc/release/test_02_append.exe
./build/build_targets/gcc/release/test_03_core_internal.exe
./build/build_targets/gcc/release/test_04_dig_t.exe
./build/build_targets/gcc/release/test_05_dig_t_constructors.exe
./build/build_targets/gcc/release/test_06_dig_t_assignations.exe
./build/build_targets/gcc/release/test_07_dig_t_conversions.exe
./build/build_targets/gcc/release/test_08_dig_t_operadores.exe
./build/build_targets/gcc/release/test_09_dig_t_algebra.exe
./build/build_targets/gcc/release/test_10_dig_t_io.exe
./build/build_targets/gcc/release/test_11_basic_types.exe
./build/build_targets/gcc/release/test_12_Int_ExpLog.exe
./build/build_targets/gcc/release/test_13_IntRoot.exe
./build/build_targets/gcc/release/test_14_primes.exe