ctest  --preset gcc-release -R test_01_math_tables
ctest  --preset gcc-release -R test_02_append
ctest  --preset gcc-release -R test_03_core_internal
ctest  --preset gcc-release -R test_04_dig_t
ctest  --preset gcc-release -R test_05_dig_t_constructors
ctest  --preset gcc-release -R test_06_dig_t_assignations
ctest  --preset gcc-release -R test_07_dig_t_conversions
ctest  --preset gcc-release -R test_08_dig_t_operadores
ctest  --preset gcc-release -R test_09_dig_t_algebra
ctest  --preset gcc-release -R test_10_dig_t_io
ctest  --preset gcc-release -R test_11_basic_types
ctest  --preset gcc-release -R test_12_Int_ExpLog
ctest  --preset gcc-release -R test_13_IntRoot
ctest  --preset gcc-release -R test_14_primes